import Head from 'next/head'
import { useEffect, useRef, useState } from 'react';
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import { SiAdobecreativecloud, SiAdobelightroom, SiAdobephotoshop, SiAdobeillustrator, SiFigma, SiJavascript, SiReact, SiNextdotjs, SiTailwindcss } from 'react-icons/si'

export default function Home() {

  const [scrollPosition, setScrollPosition] = useState(0);

  useEffect(() => {
    const updatePosition = () => {
      setScrollPosition(window.pageYOffset);
    }
    window.addEventListener("scroll", updatePosition);
    updatePosition();
    return () => window.removeEventListener("scroll", updatePosition);
  }, []);

  

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <section className={`min-h-[70vh] md:min-h-screen min-w-full grid place-items-center transition-all duration-500 ${scrollPosition > 0 ? 'mb-0 md:-mb-32' : ' mb-20'}`}>

          <div className={`flex overflow-hidden transition-all duration-500 absolute ${scrollPosition > 0 ? ' w-[90%] h-[60%] rounded-3xl' : 'w-[100%] h-[80%] md:h-[100%]'}`}>

                    <video autoPlay muted loop playsInline id="intro" className={`invisible md:visible absolute object-cover ${scrollPosition > 0 ? ' h-full w-full rounded-3xl' : 'h-full w-full'}`}>
                      <source src="intro.mp4" type="video/mp4"></source>
                    </video>
                    
                    <img className={`absolute object-cover ${scrollPosition > 0 ? ' h-full w-full rounded-3xl' : 'h-full w-full'} md:invisible `} src='omenbg.png'></img>

            <div className={`flex-1 grid content-center justify-center p-10 md:p-20 z-30`}>
              <h2 className={` text-white text-5xl font-bold`}>
                An online experience like no other.
              </h2>
              <p  className={` text-gray-light text-2xl pt-10`}>
                The digital world is rapidly growing. We will worry about that. You focus on what is important to you.
              </p>
              
            </div>

            <div className={`flex-0 absolute md:flex-1 md:relative`}>
                
            </div>
          </div>          

      </section>



      <section className=" bg-white min-w-full  grid place-items-center">
        <div className="grid place-items-center">
            <h2 className=" text-blue text-3xl font-bold text-center md:">
              Omen Digital is a online content management agency.
            </h2>
            <p  className={` text-blue text-2xl pt-5 md:pt-10 text-center w-10/12 md:w-6/12`}>
                With Omen, we will take care of all your online content. We create clean, professional content for your social media and websites.
            </p>
            <p className={` text-gray text-l pt-8 md:pt-10 w-10/12 text-center font-bold`}>
              Here are some tools we use to help you.
            </p>
            <p  className={`flex min-w-full text-gray text-3xl p-8 justify-between md:pl-20 md:pr-20 md:pb-14`}>
              <div>
                <SiAdobecreativecloud/>
              </div>
              <div>
                <SiAdobelightroom/>      
              </div>
              <div>
                <SiAdobephotoshop/>
              </div>
              <div>
                <SiAdobeillustrator/>
              </div>
              <div>
                <SiFigma/>
              </div>
              <div>
                <SiJavascript/>
              </div>
              <div>
                <SiReact/>
              </div>
              <div>
                <SiNextdotjs/>
              </div>              
              <div>
                <SiTailwindcss/> 
              </div>
            </p>
        </div>
      </section>



      <section className="grid place-items-center min-h-screen min-w-full relative bg-green">
                <img className='absolute object-cover h-full w-full' src='omenbg.png'></img>
            <h2 className=" z-10 text-white text-4xl font-bold underline">
              Hello world!
            </h2>
      </section>
      <footer>
      </footer>
    </div>
  )
}
