import Head from 'next/head'
import { useEffect, useState } from 'react';
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import { SiAdobecreativecloud, SiAdobelightroom, SiAdobephotoshop, SiAdobeillustrator, SiFigma, SiJavascript, SiReact, SiNextdotjs, SiTailwindcss } from 'react-icons/si'

export default function Home() {

  const [scrollPosition, setScrollPosition] = useState(0);

  useEffect(() => {
    const updatePosition = () => {
      setScrollPosition(window.pageYOffset);
    }
    window.addEventListener("scroll", updatePosition);
    updatePosition();
    return () => window.removeEventListener("scroll", updatePosition);
  }, []);

  return (
    <div className=' bg-orange-600'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <section className={` object-cover bg-transparent min-h-screen min-w-full grid place-items-center relative`}>
 
                 

          <div className={`flex transition-all duration-500 bg-gray absolute ${scrollPosition > 0 ? ' w-[90vw] h-[80vh] rounded-3xl' : 'h-screen w-full'}`}>

                    <video autoPlay muted loop playsInline id="intro" className={`absolute object-cover ${scrollPosition > 0 ? ' h-full w-full rounded-3xl' : 'h-full w-full'}`}>
                      <source src="intro.mp4" type="video/mp4"></source>
                    </video>
                    
            <div className={`flex-1 grid content-center justify-center pl-20 z-30`}>
              <h2 className={` text-white text-5xl font-bold`}>
                An online experience like no other.
              </h2>
              <p  className={` text-gray-light text-2xl pt-10`}>
                The digital world is rapidly growing. We will worry about that. You focus on what is important to you.
              </p>
            </div>
           <div  className={`flex-1 grid content-center justify-center`}> 
            {/*   <img src="landing-image.png" alt="landing image" className=''/>*/}
            </div>
          </div>          

      </section>



      <section className=" bg-white min-w-full  grid place-items-center">
        <div className="grid place-items-center">
            <h2 className=" text-blue text-3xl font-bold w-6/12 text-center">
              Omen Digital is a online content management agency.
            </h2>
            <p  className={` text-blue text-2xl pt-10 w-6/12 text-center`}>
                With Maven, we will take care of all your online content. We create clean, professional content for your social media and websites.
            </p>
            <p className={` text-gray text-l pt-16 w-10/12 text-center font-bold`}>
              Here are some tools we use to help you.
            </p>
            <p  className={`flex min-w-full text-gray text-3xl pl-10 pr-10 pt-10 pb-20 justify-between`}>
              <div>
                <SiAdobecreativecloud/>
              </div>
              <div>
                <SiAdobelightroom/>      
              </div>
              <div>
                <SiAdobephotoshop/>
              </div>
              <div>
                <SiAdobeillustrator/>
              </div>
              <div>
                <SiFigma/>
              </div>
              <div>
                <SiJavascript/>
              </div>
              <div>
                <SiReact/>
              </div>
              <div>
                <SiNextdotjs/>
              </div>              
              <div>
                <SiTailwindcss/> 
              </div>
            </p>
        </div>
      </section>



      <section className=" bg-blue min-h-screen min-w-full">
            <h2 className=" text-white text-4xl font-bold underline">
              Hello world!
            </h2>
      </section>
      <footer>
      </footer>
    </div>
  )
}
